import { afterEach, describe, expect, test } from 'vite-plus/test'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { usewagen } from '../src/vite'

const fixtureDir = resolve(import.meta.dirname, '__fixtures__/parsers')
const dtsPath = resolve(import.meta.dirname, '__fixtures__/usewagen.d.ts')

function createFixture(name: string, content: string) {
  if (!existsSync(fixtureDir)) mkdirSync(fixtureDir, { recursive: true })
  writeFileSync(resolve(fixtureDir, name), content, 'utf-8')
}

function cleanup() {
  if (existsSync(resolve(import.meta.dirname, '__fixtures__'))) {
    rmSync(resolve(import.meta.dirname, '__fixtures__'), { recursive: true })
  }
}

describe('usewagen plugin', () => {
  afterEach(() => cleanup())

  test('returns a plugin with correct name', () => {
    const plugin = usewagen()

    expect(plugin.name).toBe('usewagen')
  })

  test('resolves virtual module id', () => {
    const plugin = usewagen()
    const resolveId = plugin.resolveId as (id: string) => string | undefined

    expect(resolveId('virtual:usewagen')).toBe('\0virtual:usewagen')
    expect(resolveId('other-module')).toBeUndefined()
  })

  test('generates correct dts structure', () => {
    createFixture(
      'pagination.ts',
      `
import { defineParser, parseAsStringLiteral } from 'usewagen'

export const parseAsPage = defineParser({
  get: v => Number(v),
  set: v => String(v),
})

export const parseAsSort = parseAsStringLiteral(['asc', 'desc'])
`,
    )

    const plugin = usewagen({ dirs: fixtureDir, dts: dtsPath })
    const configResolved = plugin.configResolved as (config: { root: string }) => void
    configResolved({ root: import.meta.dirname })

    const content = readFileSync(dtsPath, 'utf-8')

    expect(content).toMatchInlineSnapshot(`
      "// Auto-generated by usewagen/vite — do not edit
      export {}

      declare module 'usewagen' {
        interface ParserRegistry {
          parseAsPage: typeof import('./parsers/pagination')['parseAsPage']
          parseAsSort: typeof import('./parsers/pagination')['parseAsSort']
        }
      }
      "
    `)
  })

  test('generates virtual module with registerParser calls', () => {
    createFixture(
      'pagination.ts',
      `
import { defineParser, parseAsStringLiteral } from 'usewagen'

export const parseAsPage = defineParser({
  get: v => Number(v),
  set: v => String(v),
})

export const parseAsSort = parseAsStringLiteral(['asc', 'desc'])
`,
    )

    const plugin = usewagen({ dirs: fixtureDir, dts: dtsPath })
    const configResolved = plugin.configResolved as (config: { root: string }) => void
    configResolved({ root: import.meta.dirname })

    const load = plugin.load as (id: string) => string | undefined
    const content = load('\0virtual:usewagen')!.replaceAll(fixtureDir, '<parsers>')

    expect(content).toMatchInlineSnapshot(`
      "import { registerParser } from 'usewagen'

      import { parseAsPage, parseAsSort } from '<parsers>/pagination.ts'

      registerParser('parseAsPage', parseAsPage)
      registerParser('parseAsSort', parseAsSort)
      "
    `)
  })

  test('ignores function exports (factories)', () => {
    createFixture(
      'factory.ts',
      `
import { defineParser } from 'usewagen'

export function parseAsCustom(values: string[]) {
  return defineParser({ get: v => v, set: v => v })
}

export const parseAsValid = defineParser({
  get: v => v,
  set: v => v,
})
`,
    )

    const plugin = usewagen({ dirs: fixtureDir, dts: dtsPath })
    const configResolved = plugin.configResolved as (config: { root: string }) => void
    configResolved({ root: import.meta.dirname })

    const load = plugin.load as (id: string) => string | undefined
    const content = load('\0virtual:usewagen')!

    expect(content).toContain('parseAsValid')
    expect(content).not.toContain('parseAsCustom')
  })

  test('ignores .d.ts files', () => {
    createFixture(
      'types.d.ts',
      `
export const parseAsIgnored = {}
`,
    )
    createFixture(
      'real.ts',
      `
export const parseAsReal = defineParser({ get: v => v, set: v => v })
`,
    )

    const plugin = usewagen({ dirs: fixtureDir, dts: dtsPath })
    const configResolved = plugin.configResolved as (config: { root: string }) => void
    configResolved({ root: import.meta.dirname })

    const load = plugin.load as (id: string) => string | undefined
    const content = load('\0virtual:usewagen')!

    expect(content).toContain('parseAsReal')
    expect(content).not.toContain('parseAsIgnored')
  })

  test('handles empty directory', () => {
    if (!existsSync(fixtureDir)) mkdirSync(fixtureDir, { recursive: true })

    const plugin = usewagen({ dirs: fixtureDir, dts: dtsPath })
    const configResolved = plugin.configResolved as (config: { root: string }) => void
    configResolved({ root: import.meta.dirname })

    const load = plugin.load as (id: string) => string | undefined
    const content = load('\0virtual:usewagen')!

    expect(content).toContain("import { registerParser } from 'usewagen'")
    expect(content).not.toContain('parseAs')
  })

  test('handles non-existent directory', () => {
    const plugin = usewagen({ dirs: '/nonexistent/path', dts: false })
    const configResolved = plugin.configResolved as (config: { root: string }) => void
    configResolved({ root: import.meta.dirname })

    const load = plugin.load as (id: string) => string | undefined
    const content = load('\0virtual:usewagen')!

    expect(content).not.toContain('parseAs')
  })

  test('scans nested directories', () => {
    const nestedDir = resolve(fixtureDir, 'nested')
    mkdirSync(nestedDir, { recursive: true })
    writeFileSync(
      resolve(nestedDir, 'deep.ts'),
      `export const parseAsDeep = defineParser({ get: v => v, set: v => v })`,
      'utf-8',
    )

    const plugin = usewagen({ dirs: fixtureDir, dts: dtsPath })
    const configResolved = plugin.configResolved as (config: { root: string }) => void
    configResolved({ root: import.meta.dirname })

    const load = plugin.load as (id: string) => string | undefined
    const content = load('\0virtual:usewagen')!

    expect(content).toContain('parseAsDeep')
  })

  test('disables dts generation when dts is false', () => {
    createFixture(
      'noop.ts',
      `export const parseAsNoop = defineParser({ get: v => v, set: v => v })`,
    )

    const plugin = usewagen({ dirs: fixtureDir, dts: false })
    const configResolved = plugin.configResolved as (config: { root: string }) => void
    configResolved({ root: import.meta.dirname })

    expect(existsSync(dtsPath)).toBe(false)
  })
})
