import type { ParserEntry } from './scan'

import { dirname, relative } from 'node:path'

const BANNER = '// Auto-generated by usewagen/vite — do not edit'

function toPosix(path: string): string {
  return path.replace(/\\/g, '/')
}

export function generateModule(entries: ParserEntry[]): string {
  const byFile = new Map<string, string[]>()
  for (const { name, file } of entries) {
    const names = byFile.get(file) ?? []
    names.push(name)
    byFile.set(file, names)
  }

  const lines: string[] = [BANNER]
  for (const [file, names] of byFile) {
    lines.push(`import { ${names.join(', ')} } from ${JSON.stringify(toPosix(file))}`)
  }
  lines.push('')

  if (entries.length === 0) {
    lines.push('export const parsers = {}', '')
    return lines.join('\n')
  }

  lines.push('export const parsers = {')
  for (const { name } of entries) lines.push(`  ${name},`)
  lines.push('}', '')

  return lines.join('\n')
}

export function generateDeclaration(entries: ParserEntry[], dtsPath: string): string {
  const dtsDir = dirname(dtsPath)
  const lines: string[] = [
    BANNER,
    '/// <reference types="usewagen/client" />',
    'export {}',
    '',
    "declare module 'usewagen' {",
    '  interface CustomParsers {',
  ]

  for (const { name, file } of entries) {
    const rel = toPosix(relative(dtsDir, file)).replace(/\.m?[jt]s$/, '')
    const specifier = rel.startsWith('.') ? rel : `./${rel}`
    lines.push(`    ${name}: typeof import('${specifier}')['${name}']`)
  }

  lines.push('  }', '}', '')
  return lines.join('\n')
}
