import type { ParserEntry } from './scan'

import { basename, dirname, extname, join, relative, sep } from 'node:path'

const BANNER = '// Auto-generated by usewagen/vite — do not edit'

function toPosix(path: string): string {
  return path.split(sep).join('/')
}

function toSpecifier(from: string, file: string): string {
  const target = relative(from, file)
  const withoutExtension = join(dirname(target), basename(target, extname(target)))
  const specifier = toPosix(withoutExtension)

  return specifier.startsWith('.') ? specifier : `./${specifier}`
}

export function generateModule(entries: ParserEntry[]): string {
  const byFile = new Map<string, string[]>()
  for (const { name, file } of entries) {
    const names = byFile.get(file) ?? []
    names.push(name)
    byFile.set(file, names)
  }

  const lines: string[] = [BANNER]
  for (const [file, names] of byFile) {
    lines.push(`import { ${names.join(', ')} } from ${JSON.stringify(toPosix(file))}`)
  }
  lines.push('')

  if (entries.length === 0) {
    lines.push('export const parsers = {}', '')
    return lines.join('\n')
  }

  lines.push('export const parsers = {')
  for (const { name } of entries) lines.push(`  ${name},`)
  lines.push('}', '')

  return lines.join('\n')
}

export function generateDeclaration(entries: ParserEntry[], dtsPath: string): string {
  const dtsDir = dirname(dtsPath)
  const lines: string[] = [
    BANNER,
    '/// <reference types="usewagen/client" />',
    'export {}',
    '',
    "declare module 'usewagen' {",
    '  interface CustomParsers {',
  ]

  for (const { name, file } of entries) {
    lines.push(`    ${name}: typeof import('${toSpecifier(dtsDir, file)}')['${name}']`)
  }

  lines.push('  }', '}', '')
  return lines.join('\n')
}
