import type { Plugin } from 'vite-plus'

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, dirname, relative, resolve } from 'node:path'
import { isBuiltinParserName } from '../parser/resolve'
import { ErrorCodes, getMessage } from '../messages'

const VIRTUAL_ID = 'virtual:usewagen'
const RESOLVED_VIRTUAL_ID = `\0${VIRTUAL_ID}`

export interface UsewagenPluginOptions {
  /**
   * Directory or directories to scan for parser files.
   * @default 'src/parsers'
   */
  dirs?: string | string[]
  /**
   * Output path for the generated `.d.ts` file, or `false` to disable.
   * @default 'usewagen.d.ts'
   */
  dts?: string | false
}

interface ParsedExport {
  name: string
  filePath: string
}

function extractParserExports(filePath: string): string[] {
  const content = readFileSync(filePath, 'utf-8')
  const names: string[] = []

  const constRegex = /export\s+const\s+(parseAs\w+)/g
  let match: RegExpExecArray | null
  while ((match = constRegex.exec(content)) !== null) {
    const name = match[1]
    if (isBuiltinParserName(name)) {
      console.warn(getMessage(ErrorCodes.RESERVED_PARSER_NAME), name, filePath)
      continue
    }
    names.push(name)
  }

  return names
}

function scanDirectory(dir: string): ParsedExport[] {
  if (!existsSync(dir)) return []

  const exports: ParsedExport[] = []
  const files = readdirSync(dir, { withFileTypes: true })

  for (const file of files) {
    if (file.isDirectory()) {
      exports.push(...scanDirectory(resolve(dir, file.name)))
      continue
    }

    if (!/\.(ts|mts)$/.test(file.name) || file.name.endsWith('.d.ts')) continue

    const filePath = resolve(dir, file.name)
    const names = extractParserExports(filePath)
    for (const name of names) {
      exports.push({ name, filePath })
    }
  }

  return exports
}

function generateDts(exports: ParsedExport[], dtsPath: string): string {
  const dtsDir = dirname(dtsPath)
  const lines: string[] = [
    '// Auto-generated by usewagen/vite — do not edit',
    'export {}',
    '',
    "declare module 'usewagen' {",
    '  interface CustomParsers {',
  ]

  for (const { name, filePath } of exports) {
    const rel = relative(dtsDir, filePath).replace(/\\/g, '/').replace(/\.ts$/, '')
    const importPath = rel.startsWith('.') ? rel : `./${rel}`
    lines.push(`    ${name}: typeof import('${importPath}')['${name}']`)
  }

  lines.push('  }', '}', '')
  return lines.join('\n')
}

function generateVirtualModule(exports: ParsedExport[]): string {
  const lines: string[] = ["import { registerParser } from 'usewagen/registry'", '']

  const byFile = new Map<string, string[]>()
  for (const { name, filePath } of exports) {
    const names = byFile.get(filePath) ?? []
    names.push(name)
    byFile.set(filePath, names)
  }

  for (const [filePath, names] of byFile) {
    lines.push(`import { ${names.join(', ')} } from '${filePath}'`)
  }

  lines.push('')
  for (const { name } of exports) {
    lines.push(`registerParser('${name}', ${name})`)
  }

  lines.push('')
  return lines.join('\n')
}

export function usewagen(options: UsewagenPluginOptions = {}): Plugin {
  const { dirs: rawDirs = 'src/parsers', dts = 'usewagen.d.ts' } = options

  let root = ''
  let resolvedDirs: string[] = []
  let dtsPath = ''

  function resolvePaths() {
    const dirArray = Array.isArray(rawDirs) ? rawDirs : [rawDirs]
    resolvedDirs = dirArray.map(d => resolve(root, d))
    if (dts !== false) {
      dtsPath = resolve(root, dts)
    }
  }

  function scan(): ParsedExport[] {
    const exports: ParsedExport[] = []
    for (const dir of resolvedDirs) {
      exports.push(...scanDirectory(dir))
    }
    return exports
  }

  function writeDts(exports: ParsedExport[]) {
    if (dts === false) return
    const content = generateDts(exports, dtsPath)
    const dir = dirname(dtsPath)
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    const existing = existsSync(dtsPath) ? readFileSync(dtsPath, 'utf-8') : ''
    if (existing !== content) writeFileSync(dtsPath, content, 'utf-8')
  }

  return {
    name: 'usewagen',

    configResolved(config) {
      root = config.root
      resolvePaths()
      writeDts(scan())
    },

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_VIRTUAL_ID
    },

    load(id) {
      if (id === RESOLVED_VIRTUAL_ID) {
        return generateVirtualModule(scan())
      }
    },

    configureServer(server) {
      for (const dir of resolvedDirs) {
        server.watcher.add(dir)
      }
      server.watcher.on('all', (event, path) => {
        if (!resolvedDirs.some(d => path.startsWith(d))) return
        if (!/\.(ts|mts)$/.test(basename(path))) return
        if (event === 'add' || event === 'unlink' || event === 'change') {
          const exports = scan()
          writeDts(exports)
          const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID)
          if (mod) server.moduleGraph.invalidateModule(mod)
        }
      })
    },
  }
}

export default usewagen
