import type { ParserEntry } from '../../src/vite/scan'

import { describe, expect, test } from 'vite-plus/test'
import { resolve, sep } from 'node:path'

import { generateDeclaration, generateModule } from '../../src/vite/generate'

const entries: ParserEntry[] = [
  { name: 'parseAsPage', file: '/app/src/parsers/pagination.ts' },
  { name: 'parseAsSort', file: '/app/src/parsers/pagination.ts' },
  { name: 'parseAsMoney', file: '/app/src/parsers/money.ts' },
]

describe('generateModule', () => {
  test('groups the imports per file and exports one table', () => {
    expect(generateModule(entries)).toMatchInlineSnapshot(`
      "// Auto-generated by usewagen/vite — do not edit
      import { parseAsPage, parseAsSort } from "/app/src/parsers/pagination.ts"
      import { parseAsMoney } from "/app/src/parsers/money.ts"

      export const parsers = {
        parseAsPage,
        parseAsSort,
        parseAsMoney,
      }
      "
    `)
  })

  test('emits an empty table when nothing was found', () => {
    expect(generateModule([])).toMatchInlineSnapshot(`
      "// Auto-generated by usewagen/vite — do not edit

      export const parsers = {}
      "
    `)
  })

  test('writes posix separators so the specifier survives Windows', () => {
    const generated = generateModule([
      { name: 'parseAsMoney', file: resolve('/app/parsers/money.ts') },
    ])

    expect(generated).toContain('/app/parsers/money.ts"')
    expect(generated).not.toContain('\\')
  })

  test.skipIf(sep !== '/')('a backslash in a posix file name is kept verbatim', () => {
    const generated = generateModule([{ name: 'parseAsMoney', file: '/app/we\\ird.ts' }])

    expect(generated).toContain(String.raw`from "/app/we\\ird.ts"`)
  })

  test('quotes the specifier so paths with spaces stay valid', () => {
    const generated = generateModule([{ name: 'parseAsMoney', file: '/my app/money.ts' }])

    expect(generated).toContain('from "/my app/money.ts"')
  })
})

describe('generateDeclaration', () => {
  test('augments CustomParsers with paths relative to the dts', () => {
    expect(generateDeclaration(entries, '/app/usewagen.d.ts')).toMatchInlineSnapshot(`
      "// Auto-generated by usewagen/vite — do not edit
      /// <reference types="usewagen/client" />
      export {}

      declare module 'usewagen' {
        interface CustomParsers {
          parseAsPage: typeof import('./src/parsers/pagination')['parseAsPage']
          parseAsSort: typeof import('./src/parsers/pagination')['parseAsSort']
          parseAsMoney: typeof import('./src/parsers/money')['parseAsMoney']
        }
      }
      "
    `)
  })

  test('stays a valid module when nothing was found', () => {
    const declaration = generateDeclaration([], '/app/usewagen.d.ts')

    expect(declaration).toContain('export {}')
    expect(declaration).toContain('interface CustomParsers {')
    expect(declaration).not.toContain('parseAs')
  })

  test('prefixes an upward path so it stays a relative specifier', () => {
    const declaration = generateDeclaration(
      [{ name: 'parseAsMoney', file: '/app/src/parsers/money.ts' }],
      '/app/types/usewagen.d.ts',
    )

    expect(declaration).toContain("import('../src/parsers/money')")
  })

  test('drops every module extension it may have scanned', () => {
    for (const file of ['/app/money.mts', '/app/money.js', '/app/money.mjs']) {
      const declaration = generateDeclaration(
        [{ name: 'parseAsMoney', file }],
        '/app/usewagen.d.ts',
      )

      expect(declaration).toContain("import('./money')")
    }
  })
})
